version: 2

project_name: go-gradient

builds:
  - skip: true

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "^perf:"
      - "^build:"
  groups:
    - title: "✨ Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "📚 Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: "🔧 Others"
      order: 999

release:
  github:
    owner: fuabioo
    name: go-gradient
  
  mode: replace
  
  draft: false
  prerelease: auto
  make_latest: true
  
  name_template: "v{{ .Version }}"
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/fuabioo/go-gradient/compare/{{ if .PreviousTag }}{{ .PreviousTag }}{{ else }}{{ .Tag }}{{ end }}...{{ .Tag }}
  extra_files:
    - glob: "*.md"
    - glob: "LICENSE"

announce:
  skip: true